app = "math-learning-app-backend"
primary_region = "hkg"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  REPLICATE_API_TOKEN = "r8_eGzwxuZM1YLmu2YoPPVQKizCZ4KwLi00Obptf"
  DEEPSEEK_API_KEY = "sk-gnocejrrpjhfwpubniyokhgobfqcaqgxkeoixnrooweddurx"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "math_app_data"
  destination = "/data"
