app = "math-learning-app-backend"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  REPLICATE_API_TOKEN = "${Replicate_API_TOKEN}"
  DEEPSEEK_API_KEY = "sk-gnocejrrpjhfwpubniyokhgobfqcaqgxkeoixnrooweddurx"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source = "math_app_data"
  destination = "/data"
